In [35]:
import numpy as np

# Q1 Write functions, along with proper code documentation and formatting;

## (a) To check whether a number is prime or not


In [36]:
def isprime(num):                       # defining a function isprime
    for n in range (2, int(num**0.5)+1):   # using for loop to find prime no.
        if num%n == 0:
            return False
    return True
print(isprime(7))
print(isprime(8))

True
False


## (b) To find the longest word in a sentence given as input by the user

In [37]:
# longest word
sentence = input("Enter sentences:   ")    # reading sentences from users

# finding longest word
longest = max(sentence.split(), key=len)

# display longest word
print("Longest word is:  ", longest)
print("And its length is  ", len(longest))

Enter sentences:   abhishek
Longest word is:   abhishek
And its length is   8


## (c)  To find how many times a given user-inputted substring is repeated in another user inputted string

In [23]:
# here i am taken some names of computer game.
# defined with short name.

game_of_throne = "Q"
game_of_takken = "P"
game_of_Cycling = "P"
game_of_Bike = "T"
game_of_GTA = "P"

# checking defined names 
result = (game_of_throne,game_of_takken,game_of_Cycling,game_of_Bike,game_of_GTA)
print("Result:    ",result)

# counting how many times user or i have entered a same name.
print("Counting how many times is entered by user:  ",result.count("P"))

Result:     ('Q', 'P', 'P', 'T', 'P')
Counting how many times is entered by user:   3


# Q2 Create the following class with the given attributes and methods

## (a) Standard -

### (i) Attributes: Std name, No of enrolled students, Overall GPA

In [38]:
# creating class of student
class student(object):
    
    # attributes
    def __init__(self, name, enrolled, GPA):
        self.name = name
        self.enrolled = enrolled
        self.GPA = GPA

# filling name, enrolled and gpa
p1 = student("abhishek",5,60)        
  
# printing output
print("Name  ",p1.name)
print("Student enrolled  ",p1.enrolled)
print("GPA  ",p1.GPA)

Name   abhishek
Student enrolled   5
GPA   60


### (ii) Methods: getStd, getEnrolled, getOGPA

In [39]:
# creating class of student
class student(object):
    
    # attributes
    def __init__(self, name, enrolled, GPA):
        self.name = name
        self.enrolled = enrolled
        self.GPA = GPA
    
    # making method getStd, getEnrolled, getOGPA
    def getStd(self):
        print("Student name is " + self.name)
        
    def getEnrolled(self):
        print("Student enrolled ", self.enrolled)
        
    def getOGPA(self):
        print("Overall GDP is ", self.GPA)

p1 = student("Abhishek",5, 66)     # attribute info

# calling method 
p1.getStd()
p1.getEnrolled()
p1.getOGPA()

Student name is Abhishek
Student enrolled  5
Overall GDP is  66


## (b) Students class with Standard as its super class

### (i) Attributes: Name,Roll No., Standard, Math marks, English Marks, Science Marks, Social Marks

In [45]:
# parent class
class parent:
    def __init__(self,  name, roll_no, standard, math, english, science, social):
        self.name = name
        self.roll_no = roll_no
        self.standard = standard
        self.math = math
        self.english = english
        self.science = science
        self.social = social
    
    # methods
    def getStd(self):
        print("Student name is " + self.name)
        
    def getroll(self):
        print("Student roll number ", self.roll_no)
        
    def getstandard(self):
        print("standard is " + self.standard)
     
    def getmath(self):
        print("Maths marks is ", self.math)
        
    def getenglish(self):
        print("English marks is ", self.english)
        
    def getscience(self):
        print("Science marks is", self.science)
        
    def getsocial(self):
        print("Social science marks is ", self.social)

# child class
class child(parent):
    def __init__(self,  name, roll_no, standard, math, english, science, social):
        super().__init__( name, roll_no, standard, math, english, science, social)

# attribute info        
x = child("ram",25,"4th",50,60,70,80)

# calling method
x.getStd()
x.getroll()
x.getstandard()
x.getmath()
x.getenglish()
x.getscience()
x.getsocial()

Student name is ram
Student roll number  25
standard is 4th
Maths marks is  50
English marks is  60
Science marks is 70
Social science marks is  80


### (ii) Methods: getName, getRollNo, getStd, getGPA

In [3]:
# creating class of student
class student(object):
    
    # attributes
    def __init__(self, name, roll_no, std, GPA):
        self.name = name
        self.roll_no = roll_no
        self.std = std
        self.GPA = GPA
    
    # making method getStd, getroll, getgpa
    def getName(self):
        print("Student name is " + self.name)
        
    def getRoll(self):
        print("Student enrolled ", self.roll_no)
        
    def getStd(self):
        print("Standard is ", self.std)
        
    def getGpa(self):
        print("Overall GDP is ", self.GPA)

p1 = student("Abhishek",5, "4th", 66)     # attribute info

# calling method 
p1.getName()
p1.getRoll()
p1.getStd()
p1.getGpa()

Student name is Abhishek
Student enrolled  5
Standard is  4th
Overall GDP is  66


## (c) Explanation

### (i) getName, getRollNo, getStd methods should give the name, roll number and standard of the student. 

In [5]:
# here i am using getName, getRoll, getStd to make the information of the student and then i have given attribute information.
# then i am calling method in the last.



# creating class of student
class student(object):
    
    # attributes
    def __init__(self, name, roll_no, std):
        self.name = name
        self.roll_no = roll_no
        self.std = std
    
    # making method getStd, getroll, getgpa
    def getName(self):
        print("Student name is " + self.name)
        
    def getRoll(self):
        print("Student enrolled ", self.roll_no)
        
    def getStd(self):
        print("Standard is ", self.std)
        

p1 = student("Abhishek",5, "4th")     # attribute info

# calling method 
p1.getName()
p1.getRoll()
p1.getStd()


Student name is Abhishek
Student enrolled  5
Standard is  4th


### (ii) getGPA should give the average marks of math,english, science and social marks scaled to 10-points. Same applies for all the attributes and methods in the Standard superclass.

In [61]:
# creating class of student
class student(object):
    
    # attributes
    def __init__(self, english, math, computer):
        self.english = english
        self.math = math
        self.computer = computer
        
    
    
    # making method getStd, getroll, getgpa
    def getsubject(self):
        print("English marks is:  ", self.english)
        print("Maths:  ",self.math)
        print("Computer:  ",self.computer)
    
    # making another function to find average.
    def getavg(lst):
        return sum(lst) / len(lst)
    
    # subject marks defined again.
    lst = [50,60,70]
    
    average = getavg(lst)
    print("Average =", round(average, 2))
        
p1 = student(50,60,70)     # attribute info
p1.getsubject()

Average = 60.0
English marks is:   50
Maths:   60
Computer:   70


# Q3 Answer the following;

## (a) Create a function to find the indices of a parameter passed to the function in a user inputted array. Ex: f(0,[1,2,0,0,4]) gives [2,3] as output

In [10]:
# importing array lib
from array import *

# array of empty set
arr = array('i',[])

# user define length of array
n = int(input("Enter the length of the array:   "))


# making loop, when user enter the length of array it will process
# and execute it according to user defined length
for i in range(n):
    x = int(input("Enter the value for search:  "))
    arr.append(x)
    
    
print(arr)


# entering value for search for indices
val = int(input("Enter the value for search:   "))

k = 0

# making loop to find indexes
for e in arr:
    if e==val:
        print(k)
        #break
        
    k+=1     # using inreament to find last of zero 0
    
#print(arr.index(val))

Enter the length of the array:   5
Enter the value for search:  1
Enter the value for search:  2
Enter the value for search:  0
Enter the value for search:  0
Enter the value for search:  4
array('i', [1, 2, 0, 0, 4])
Enter the value for search:   0
2
3


## (b) Create a random vector of size 30 and find the mean value

In [5]:
import numpy as np     # using numpy for fast process and calculation

# finding random no. to 30
x = np.random.random(30)
print("Original array:  ")
print(x)

# sorting array or mean
x.sort()
print("Sorted array:  ")
print(x)

Original array:  
[0.7541962  0.91440479 0.12212231 0.42160644 0.95992138 0.8009675
 0.55085353 0.2763845  0.87297642 0.21174005 0.61737896 0.06203401
 0.48440068 0.75752404 0.70071206 0.77846058 0.95868592 0.09283118
 0.06586124 0.6812923  0.02335647 0.8725591  0.5772086  0.66693854
 0.98825289 0.67445747 0.30790963 0.79337876 0.1849946  0.5044026 ]
Sorted array:  
[0.02335647 0.06203401 0.06586124 0.09283118 0.12212231 0.1849946
 0.21174005 0.2763845  0.30790963 0.42160644 0.48440068 0.5044026
 0.55085353 0.5772086  0.61737896 0.66693854 0.67445747 0.6812923
 0.70071206 0.7541962  0.75752404 0.77846058 0.79337876 0.8009675
 0.8725591  0.87297642 0.91440479 0.95868592 0.95992138 0.98825289]


## (c) Create a 2d array with 1 on its edges and 0 in all other indices

In [10]:
# using numpy for fast process and calculation
import numpy as np

# here i am finding array of 5*5
x = np.ones((5,5))
print("Original array:  ")
print(x)

# setting arrangement of indices of 1 and 0.
print("1 is on borderside and 0 should be inside in it")
x[1:-1,1:-1] = 0
print(x)

Original array:  
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 is on borderside and 0 should be inside in it
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## (d) Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [14]:
# using numpy for fast process and calculation
import numpy as np

# making matrix of ones 3*3
x = np.ones((3,3))
print("Check board pattern")

# making matrix of zeros 8*8
x = np.zeros((8,8),dtype = int)

# arranging matrix pattern
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Check board pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
